Fixed bug causing the Makefile detection to crash.
Error:  Can't call method "stringify" without a package or object
reference at ...CatalystX/AppBuilder.pm line 176.

This was because the last was operating on the new loop rather than the
original while loop it used to affect.